baseURL = 'https://noonreport.onrender.com/'
languageCode = 'ru-ru'
title = 'Noon Report'
theme = "archie"


# Site wide kill switch for Latex support
math = true
# (If math is enabled) 
## if "katex" is set to true katex will be used to render LaTex, if not MathJax will be used instead
katex = true

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[params]
  # Subtitle of the website
  # subtitle = "Половинку никто не пишет / Medium non scribitur."
  # Your name or the name of you company
  copyrightHolder = "Половинку никто не пишет"
  # Show the "Powered by Hugo-Tufte and Hugo." 
  showPoweredBy = false
  # Site wide kill switch
  hidedate = true
  # Uncomment for dark code blocks
  # codeBlocksDark = true
  



[[menu.main]]
name = "Все тексты"
url = "/post/"
weight = 2

[[menu.main]]
name = "О блоге"
url = "/about/"
weight = 3




 